name: BioJS
description: Represent all biological data on the web
url: http://biojs.net
markdown: kramdown
#pygments: false
#highlighter: pygments
timezone: UTC
encoding: utf-8
exclude: [vendor]
series:
    "101":
      desc: "Basics"
      sort: 1
    "snipspector":
      desc: "Snipspector tutorial"
      sort: 4
    "details":
      desc: "Details"
      sort: 3
    "graduates":
      desc: "Beginner tutorial"
      sort: 2
    "snipspector_adv":
      desc: "Advanced snipspector"
      sort: 5
